package com.dharam.zemoso.test;

import java.util.HashMap;
import java.util.Map.Entry;

public class Main {

	public static void main(String[] args) {
System.out.println("aaaaaaaasdadsadasasfajnavskanksvkaksvkakifianviaisviaisviasiviasviaisviasviasiviasviasivbaisviasivaisviasviasviaiviasviasivisavbiasviabisviasbviasbivbaisvbasibviabivsbaivbsaivbaibviasbviabvivbaivaaaaaaaasdadsadasasfajnavskanksvkaksvkakifianviaisviaisviasiviasviaisviasviasiviasviasivbaisviasivaisviasviasviaiviasviasivisavbiasviabisviasbviasbivbaisvbasibviabivsbaivbsaivbaibviasbviabvivbaivaaaaaaaasdadsadasasfajnavskanksvkaksvkakifianviaisviaisviasiviasviaisviasviasiviasviasivbaisviasivaisviasviasviaiviasviasivisavbiasviabisviasbviasbivbaisvbasibviabivsbaivbsaivbaibviasbviabvivbaivaaaaaaaasdadsadasasfajnavskanksvkaksvkakifianviaisviaisviasiviasviaisviasviasiviasviasivbaisviasivaisviasviasviaiviasviasivisavbiasviabisviasbviasbivbaisvbasibviabivsbaivbsaivbaibviasbviabvivbaivaaaaaaaasdadsadasasfajnavskanksvkaksvkakifianviaisviaisviasiviasviaisviasviasiviasviasivbaisviasivaisviasviasviaiviasviasivisavbiasviabisviasbviasbivbaisvbasibviabivsbaivbsaivbaibviasbviabvivbaivaaaaaaaasdadsadasasfajnavskanksvkaksvkakifianviaisviaisviasiviasviaisviasviasiviasviasivbaisviasivaisviasviasviaiviasviasivisavbiasviabisviasbviasbivbaisvbasibviabivsbaivbsaivbaibviasbviabvivbaivaaaaaaaasdadsadasasfajnavskanksvkaksvkakifianviaisviaisviasiviasviaisviasviasiviasviasivbaisviasivaisviasviasviaiviasviasivisavbiasviabisviasbviasbivbaisvbasibviabivsbaivbsaivbaibviasbviabvivbaivaaaaaaaasdadsadasasfajnavskanksvkaksvkakifianviaisviaisviasiviasviaisviasviasiviasviasivbaisviasivaisviasviasviaiviasviasivisavbiasviabisviasbviasbivbaisvbasibviabivsbaivbsaivbaibviasbviabvivbaivaaaaaaaasdadsadasasfajnavskanksvkaksvkakifianviaisviaisviasiviasviaisviasviasiviasviasivbaisviasivaisviasviasviaiviasviasivisavbiasviabisviasbviasbivbaisvbasibviabivsbaivbsaivbaibviasbviabvivbaivaaaaaaaasdadsadasasfajnavskanksvkaksvkakifianviaisviaisviasiviasviaisviasviasiviasviasivbaisviasivaisviasviasviaiviasviasivisavbiasviabisviasbviasbivbaisvbasibviabivsbaivbsaivbaibviasbviabvivbaivaaaaaaaasdadsadasasfajnavskanksvkaksvkakifianviaisviaisviasiviasviaisviasviasiviasviasivbaisviasivaisviasviasviaiviasviasivisavbiasviabisviasbviasbivbaisvbasibviabivsbaivbsaivbaibviasbviabvivbaivaaaaaaaasdadsadasasfajnavskanksvkaksvkakifianviaisviaisviasiviasviaisviasviasiviasviasivbaisviasivaisviasviasviaiviasviasivisavbiasviabisviasbviasbivbaisvbasibviabivsbaivbsaivbaibviasbviabvivbaiv".length());
		//System.out.println(new Main().solution("aaaaaaaasdadsadasasfajnavskanksvkaksvkakifianviaisviaisviasiviasviaisviasviasiviasviasivbaisviasivaisviasviasviaiviasviasivisavbiasviabisviasbviasbivbaisvbasibviabivsbaivbsaivbaibviasbviabvivbaivaaaaaaaasdadsadasasfajnavskanksvkaksvkakifianviaisviaisviasiviasviaisviasviasiviasviasivbaisviasivaisviasviasviaiviasviasivisavbiasviabisviasbviasbivbaisvbasibviabivsbaivbsaivbaibviasbviabvivbaivaaaaaaaasdadsadasasfajnavskanksvkaksvkakifianviaisviaisviasiviasviaisviasviasiviasviasivbaisviasivaisviasviasviaiviasviasivisavbiasviabisviasbviasbivbaisvbasibviabivsbaivbsaivbaibviasbviabvivbaivaaaaaaaasdadsadasasfajnavskanksvkaksvkakifianviaisviaisviasiviasviaisviasviasiviasviasivbaisviasivaisviasviasviaiviasviasivisavbiasviabisviasbviasbivbaisvbasibviabivsbaivbsaivbaibviasbviabvivbaivaaaaaaaasdadsadasasfajnavskanksvkaksvkakifianviaisviaisviasiviasviaisviasviasiviasviasivbaisviasivaisviasviasviaiviasviasivisavbiasviabisviasbviasbivbaisvbasibviabivsbaivbsaivbaibviasbviabvivbaivaaaaaaaasdadsadasasfajnavskanksvkaksvkakifianviaisviaisviasiviasviaisviasviasiviasviasivbaisviasivaisviasviasviaiviasviasivisavbiasviabisviasbviasbivbaisvbasibviabivsbaivbsaivbaibviasbviabvivbaivaaaaaaaasdadsadasasfajnavskanksvkaksvkakifianviaisviaisviasiviasviaisviasviasiviasviasivbaisviasivaisviasviasviaiviasviasivisavbiasviabisviasbviasbivbaisvbasibviabivsbaivbsaivbaibviasbviabvivbaivaaaaaaaasdadsadasasfajnavskanksvkaksvkakifianviaisviaisviasiviasviaisviasviasiviasviasivbaisviasivaisviasviasviaiviasviasivisavbiasviabisviasbviasbivbaisvbasibviabivsbaivbsaivbaibviasbviabvivbaivaaaaaaaasdadsadasasfajnavskanksvkaksvkakifianviaisviaisviasiviasviaisviasviasiviasviasivbaisviasivaisviasviasviaiviasviasivisavbiasviabisviasbviasbivbaisvbasibviabivsbaivbsaivbaibviasbviabvivbaivaaaaaaaasdadsadasasfajnavskanksvkaksvkakifianviaisviaisviasiviasviaisviasviasiviasviasivbaisviasivaisviasviasviaiviasviasivisavbiasviabisviasbviasbivbaisvbasibviabivsbaivbsaivbaibviasbviabvivbaivaaaaaaaasdadsadasasfajnavskanksvkaksvkakifianviaisviaisviasiviasviaisviasviasiviasviasivbaisviasivaisviasviasviaiviasviasivisavbiasviabisviasbviasbivbaisvbasibviabivsbaivbsaivbaibviasbviabvivbaivaaaaaaaasdadsadasasfajnavskanksvkaksvkakifianviaisviaisviasiviasviaisviasviasiviasviasivbaisviasivaisviasviasviaiviasviasivisavbiasviabisviasbviasbivbaisvbasibviabivsbaivbsaivbaibviasbviabvivbaiv"));
		//System.out.println("abbabba".substring(6, 7));
	}

	public int solution(String S) {
        
		int maxLength = 0;
		
		if(S == null){
			return maxLength; 
		}
		
		int n = S.length();
		
		if(n>0){
			HashMap<String,Integer> prefix = new HashMap<>();
			HashMap<String,Integer> suffix = new HashMap<>();
			//find prefix
			for(int i=1;i<n;i++){
				prefix.put(S.substring(0, i),1);
				suffix.put(S.substring(n-i, n), 1);
				//System.out.println(S.substring(n-i, n));
			}
			//System.out.println(prefix);
			//System.out.println(suffix);
			for(Entry<String, Integer> s : prefix.entrySet()){
				String key = s.getKey();
				if(suffix.containsKey(key)){
					maxLength = maxLength < key.length() ? key.length() : maxLength;
				}
			}
		}
		
		return maxLength;
		
    }
	
}
